(rule
 (target c_flags.sexp)
 (action
  (with-stdout-to %{target}
    (bash
     "pkg-config --cflags glesv2 |
      awk 'BEGIN { printf \"(\" } { for(i=1;i<=NF;i++) printf \"\\\"%s\\\" \", $i } END { printf \")\\n\" }'"))))

(rule
 (targets gles3_type.ml)
 (deps gles3_type.mlc c_flags.sexp)
 (action
  (with-stdout-to gles3_type.ml
  (bash "cpp $(sed 's/[()\\\"]//g' c_flags.sexp) -P %{dep:gles3_type.mlc} | grep -F -A 1000 '(*BEGIN*)' | sed \"s/'\\\"'/'/g\""))))

(library
 (name gles3)
 (public_name gles3)
 (synopsis "OpenGL ES 3 bindings")
 (modules :standard)
 (wrapped false)
 (flags (:standard -w -6-27-32 -thread))
 (ocamlopt_flags (:standard -O3))
 (virtual_modules backend)
 (libraries str unix bigarray gles3-stubs))
