name: build

on:
  pull_request:
  push:
    branches: [master]
  schedule:
    # Prime the caches every Monday
    - cron: '0 1 * * MON'

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - ubuntu-22.04
          - macos-latest
        ocaml-compiler:
          - "5.2"
          - "5.3"
          - "5.4"
          - "5.5"

    runs-on: ${{ matrix.os }}

    steps:
      - run: sudo apt-get update
        if: ${{ matrix.os == 'ubuntu-latest' }}

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: avsm/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Deps
        run: |
          opam pin add -y conf-gles2 .
          opam pin add -y gles3-stubs .
          opam install ./gles3-stubs.opam --deps-only --with-test
          opam pin add -y gles3 .
          opam install ./gles3.opam --deps-only --with-test
          opam pin add -y gles3-x11 .
          opam install ./gles3-x11.opam --deps-only --with-test
          if [ "${{ matrix.os }}" != "macos-latest" ]; then
            opam pin add -y gles3-wayland .
            opam install ./gles3-wayland.opam --deps-only --with-test
          fi

      - run: opam exec -- make

      - run: |
          opam install gles3-stubs gles3 gles3-x11
          if [ "${{ matrix.os }}" != "macos-latest" ]; then
            opam install gles3-wayland
          fi

  build-container:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        distro:
          - archlinux
          - fedora
          - opensuse
          - centos

    container:
      image: ocaml/opam:${{ matrix.distro }}
      options: --user root

    steps:
      - name: Install tools
        run: |
          case "${{ matrix.distro }}" in
            archlinux*)
              pacman -Sy --noconfirm nodejs npm git
              ;;
            fedora|centos*)
              dnf install -y nodejs npm git
              ;;
            opensuse*)
              zypper --non-interactive install nodejs npm git
              ;;
            alpine*)
              apk add --no-cache nodejs npm git
              ;;
          esac

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Fix permissions
        run: |
          chown -R opam:opam "$GITHUB_WORKSPACE"

      - name: Opam init
        run: |
          su opam -c '
            opam init --disable-sandboxing -y
            opam switch create ocaml5.5 5.5.0
            '

      - name: Deps
        run: |
          su opam -c '
            opam switch set ocaml5.5
            cd "$GITHUB_WORKSPACE"
            opam pin add -y conf-gles2 .
            opam install . --deps-only --with-test
            '

      - name: Build
        run: |
          su opam -c '
            opam switch set ocaml5.5
            cd "$GITHUB_WORKSPACE"
            opam exec -- make
            '

      - name: Pin
        run: |
          su opam -c '
            opam switch set ocaml5.5
            cd "$GITHUB_WORKSPACE"
            opam pin add -y gles3-stubs .
            opam pin add -y gles3 .
            opam pin add -y gles3-x11 .
            opam pin add -y gles3-wayland .
            '

      - name: Install
        run: |
          su opam -c '
            opam switch set ocaml5.5
            cd "$GITHUB_WORKSPACE"
            opam install gles3-stubs gles3 gles3-x11 gles3-wayland
            '
